security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: username  # Identifiant d'authentification

    firewalls:
        # Firewall pour l'authentification via json_login pour générer le token
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                
        # Firewall pour les requêtes API protégées qui nécessitent un token JWT
        
        api:
            pattern: ^/api
            provider: app_user_provider
            stateless: true
            jwt: ~
     

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/api/utilisateurs, roles: PUBLIC_ACCESS  }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }  
        - { path: ^/api/objets, roles: PUBLIC_ACCESS }  
        - { path: ^/api, roles: PUBLIC_ACCESS }
        - { path: ^/api/me, roles: PUBLIC_ACCESS }
        
